# -*- coding: utf-8 -*-
"""app trà sữa

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/141Lu_WxdDqOAMlmV8pQw2VX9GvzzJ0JQ
"""

import sys
import streamlit as st
import pandas as pd
import joblib

st.set_page_config(page_title="Dự Đoán Doanh Thu Trà Sữa", page_icon="🧋", layout="centered")

st.markdown("""
    <style>
    .stApp {
        background-color: #FFF0F5;
    }
    .main-title {
        color: #D02090;
        text-align: center;
        font-family: 'Arial';
        font-weight: bold;
    }
    div.stButton > button:first-child {
        background-color: #FF69B4;
        color: white;
        border-radius: 20px;
        border: none;
        width: 100%;
        font-weight: bold;
        transition: 0.3s;
    }
    div.stButton > button:first-child:hover {
        background-color: #FF1493;
        color: white;
    }
    .result-box {
        background-color: white;
        padding: 20px;
        border-radius: 15px;
        border-left: 10px solid #FF69B4;
        box-shadow: 2px 2px 15px rgba(0,0,0,0.1);
    }
    </style>
    """, unsafe_allow_html=True)

st.markdown("<h1 class='main-title'>🧋 PHẦN MỀM DỰ ĐOÁN DOANH THU 🧋</h1>", unsafe_allow_html=True)
st.write("<p style='text-align: center; color: #DB7093;'>Giải pháp thông minh cho chủ quán trà sữa tương lai</p>", unsafe_allow_html=True)

st.subheader("🌸 Thông số cửa hàng")
col1, col2 = st.columns(2)

with col1:
    gia_ly = st.number_input("Giá trung bình/ly (VNĐ)", value=35000, step=1000)
    khach_ngay = st.slider("Lượng khách/ngày", 0, 500, 100)
    dien_tich = st.number_input("Diện tích quán (m2)", value=30)
    nhan_vien = st.number_input("Số nhân viên", value=2)

with col2:
    vi_tri = st.selectbox("Vị trí gần trường/văn phòng?", ["Không", "Có"])
    cho_ngoi = st.selectbox("Có chỗ ngồi lại không?", ["Không", "Có"])
    delivery = st.selectbox("Có giao hàng (App) không?", ["Không", "Có"])
    doi_thu = st.number_input("Số đối thủ bán kính 500m", value=3)

vi_tri_num = 1 if vi_tri == "Có" else 0
cho_ngoi_num = 1 if cho_ngoi == "Có" else 0
delivery_num = 1 if delivery == "Có" else 0

if st.button("✨ TÍNH TOÁN DOANH THU ✨"):
    doanh_thu_uoc_tinh = (gia_ly * khach_ngay) * (1 + 0.2*vi_tri_num + 0.1*cho_ngoi_num)

    st.markdown(f"""
        <div class="result-box">
            <h3 style='color: #D02090; margin-top:0;'>Kết quả dự đoán:</h3>
            <p style='font-size: 24px; font-weight: bold; color: #FF1493;'>
                {doanh_thu_uoc_tinh:,.0F} VNĐ / ngày
            </p>
            <p style='color: #666;'>Doanh thu tháng ước tính: <b>{(doanh_thu_uoc_tinh * 30):,.0F} VNĐ</b></p>
        </div>
    """, unsafe_allow_html=True)
    st.balloons()

