# -*- coding: utf-8 -*-
"""app ba cô nàng

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BBuqgUBXb73Z-hNqcMAQvNJST69Ori5r
"""


import streamlit as st

st.set_page_config(page_title="Dự Đoán Doanh Thu Cute", page_icon="🎀", layout="centered")

st.markdown("""
    <style>

    .stApp {
        background-color: #FFF0F5;
    }


    h1, h2, h3, p {
        color: #FF69B4 !important;
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    }

    .main-title {
        color: #FF1493;
        text-align: center;
        font-weight: bold;
        text-shadow: 2px 2px #FFC0CB;
        font-size: 3em;
        background: linear-gradient(270deg, #ff9a9e, #fad0c4, #ffd1ff, #a1c4fd);
        background-size: 800% 800%;
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        animation: rainbow 10s ease infinite;
    }

    @keyframes rainbow {
       0% { background-position: 0% 50%; }
       50% { background-position: 100% 50%; }
       100% { background-position: 0% 50%; }
    }

    .stTextInput>div>div>input, .stSelectbox>div>div>div, .stSlider>div>div {
        border-radius: 20px !important;
        border: 2px solid #FFB6C1 !important;
    }

    div.stButton > button:first-child {
        background-color: #FF69B4;
        color: white;
        border-radius: 30px;
        border: 2px solid #FFC0CB;
        width: 100%;
        font-weight: bold;
        height: 3.5em;
        font-size: 1.2em;
        transition: 0.3s;
        box-shadow: 0px 4px 15px rgba(255, 105, 180, 0.4);
    }

    div.stButton > button:first-child:hover {
        background-color: #FF1493;
        transform: scale(1.02);
        border: 2px solid #FFFFFF;
    }

    .result-box {
        background-color: #FFFFFF;
        padding: 20px;
        border-radius: 25px;
        box-shadow: 0 8px 32px 0 rgba(31, 38, 135, 0.15),
                    0 0 10px rgba(255, 182, 193, 0.4);
        backdrop-filter: blur(4px);
        transition: transform 0.3s ease;
    }

    .result-box:hover {
    transform: translateY(-5px); /* Nhấp nhô nhẹ khi di chuột vào */
    box-shadow: 0 10px 40px 0 rgba(31, 38, 135, 0.25);
   }


    .stSlider [data-baseweb="slider"] {
        background-color: #FFB6C1;
    }
    </style>
    """, unsafe_allow_html=True)

st.markdown("<h1 class='main-title'>🎀 BA CÔ NÀNG 🎀</h1>", unsafe_allow_html=True)
st.write("<p style='text-align: center; font-size: 1.2em;'>🌸 Dự đoán doanh thu thông minh với phong cách kẹo ngọt 🌸</p>", unsafe_allow_html=True)

st.subheader("🧸 Thông tin quán")
col_a, col_b = st.columns(2)
with col_a:
    ten_quan = st.text_input("1. Tên quán xinh:", placeholder="Nhập tên quán...")
    loai_hinh = st.radio("3. Loại hình kinh doanh:", ["Trà sữa", "Cà phê", "Kết hợp"], horizontal=True)
with col_b:
    dia_chi_quan = st.text_input("2. Địa chỉ quán:", placeholder="Quán mình ở đâu nhỉ?...")
    thoi_gian_hd = st.selectbox(
        "4. Quán mở được lâu chưa?",
        ["Dưới 6 tháng", "6 tháng - 1 năm", "1 - 3 năm", "Trên 3 năm"]
    )

st.subheader("✨ Quy mô & Kinh doanh")
col1, col2 = st.columns(2)

with col1:
    muc_gia = st.selectbox(
        "5. Giá mỗi ly trung bình:",
        ["Dưới 20.000đ", "20.000đ - 35.000đ", "35.000đ - 50.000đ", "Trên 50.000đ"]
    )
    mat_bang = st.selectbox(
        "6. Mặt bằng quán mình là:",
        ["Mặt tiền đường lớn", "Trong hẻm", "Gần ngã tư/Khu đông người"]
    )
    doi_thu = st.selectbox(
        "7. Quanh đây có nhiều quán giống mình không?",
        ["0-2 quán", "3-5 quán", "6-10 quán", "Trên 10 quán"]
    )
    cho_ngoi = st.radio("8. Khách có chỗ ngồi lại không nè?", ["Có", "Không"], horizontal=True)

with col2:
    suc_chua = st.selectbox(
        "9. Sức chứa (người):",
        ["Dưới 20", "20-50", "50-100", "Trên 100"]
    )
    dien_tich = st.selectbox(
        "10. Diện tích quán khoảng:",
        ["Dưới 20m2", "20m2 - 50m2", "50m2 - 100m2", "Trên 100m2"]
    )
    so_nhan_vien = st.selectbox(
        "11. Team mình có bao nhiêu người?",
        ["1-2 người", "3-5 người", "6-10 người", "Trên 10 người"]
    )
    app_giao_hang = st.radio("12. Có bán trên App không?", ["Có", "Không"], horizontal=True)

st.write("---")
col3, col4 = st.columns(2)
with col3:
    doi_tuong_khach = st.selectbox(
        "13. Khách yêu của quán là ai?",
        ["Học sinh/Sinh viên", "Nhân viên văn phòng", "Gia đình", "Cả 3", "Doanh nhân"]
    )
with col4:
    vi_tri_gan = st.selectbox(
        "14. Quán nằm gần khu vực:",
        ["Trường học", "Văn phòng/Công ty", "Khu dân cư", "Trung tâm thương mại", "Trung tâm Quận 1"]
    )

khung_gio = st.selectbox("15. Lúc nào quán đông khách nhất?", ["Sáng", "Trưa", "Chiều", "Tối"])
khach_ngay = st.slider("16. Một ngày quán đón khoảng bao nhiêu khách?", 0, 500, 100)

gia_tinh_toan = 15000
if muc_gia == "20.000đ - 35.000đ": gia_tinh_toan = 27500
elif muc_gia == "35.000đ - 50.000đ": gia_tinh_toan = 42500
elif muc_gia == "Trên 50.000đ": gia_tinh_toan = 60000

he_so_app = 1.35 if app_giao_hang == "Có" else 1.0
he_so_cho_ngoi = 1.15 if cho_ngoi == "Có" else 1.0
he_so_vi_tri = 1.4 if vi_tri_gan == "Trung tâm Quận 1" else 1.2 if vi_tri_gan == "Trung tâm thương mại" else 1.0
he_so_canh_tranh = 0.7 if doi_thu == "Trên 10 quán" else 0.85 if doi_thu == "6-10 quán" else 1.0

if st.button("💖 TÍNH TOÁN DOANH THU NGAY 💖"):
    doanh_thu_ngay = (gia_tinh_toan * khach_ngay) * he_so_app * he_so_cho_ngoi * he_so_vi_tri * he_so_canh_tranh

    st.markdown(f"""
        <div class="result-box">
            <h2 style='margin-top:0;'>🍭 Kết Quả Tuyệt Vời 🍭</h2>
            <p style='color: #666; font-size: 1.1em;'>Chúc mừng <b>{ten_quan if ten_quan else "nàng"}</b> nhé!</p>
            <hr style='border: 1px solid #FFB6C1;'>
            <p style='font-size: 32px; font-weight: bold; color: #FF1493; margin-bottom: 0;'>
                {doanh_thu_ngay:,.0f} VNĐ / ngày
            </p>
            <p style='font-size: 20px; color: #FF69B4;'>Doanh thu tháng ước tính: <b>{(doanh_thu_ngay * 30):,.0f} VNĐ</b></p>
            <p style='font-size: 0.9em; color: #DB7093; font-style: italic;'>Cố gắng lên, quán sẽ ngày càng đông khách! 🌸</p>
        </div>
    """, unsafe_allow_html=True)
    st.balloons()

